In [ ]:
import numpy as np

a=np.array([1,2,3])
print(a)

print(type(a))

# array

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
np.array([[1,2,3],[4,5,6]])

# metrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.array([[[1,2,3],[4,5,6],[7,8,9]]])

# tensor 

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [10]:
np.arange(1,11,dtype=float)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
np.arange(1,11,dtype=float).reshape(5,2)

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [18]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.random.random((3,4))

array([[0.0965257 , 0.85225509, 0.25348136, 0.4404658 ],
       [0.68874935, 0.22510149, 0.84520275, 0.63189197],
       [0.07862795, 0.30794331, 0.9742018 , 0.89475486]])

In [23]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [24]:
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [25]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])