Some Important Function Of Numpy

In [2]:
import numpy as np
a=np.random.randint(1,100,15)

a

array([41, 84, 63, 91, 17, 93, 38, 34, 24, 30, 23, 50, 78, 33, 94])

In [4]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[14, 35, 79, 38],
       [ 9,  1, 77, 26],
       [50,  8, 54,  2],
       [20,  1, 47, 68],
       [59, 72, 39, 43],
       [36, 81,  9, 31]])

In [5]:
np.sort(a)

array([17, 23, 24, 30, 33, 34, 38, 41, 50, 63, 78, 84, 91, 93, 94])

In [6]:
np.sort(a)[::-1]

array([94, 93, 91, 84, 78, 63, 50, 41, 38, 34, 33, 30, 24, 23, 17])

In [8]:
np.sort(b)

# in 2 d matrix by default sorting based on row wise


array([[14, 35, 38, 79],
       [ 1,  9, 26, 77],
       [ 2,  8, 50, 54],
       [ 1, 20, 47, 68],
       [39, 43, 59, 72],
       [ 9, 31, 36, 81]])

In [10]:
np.sort(b,axis=0)

# to give axis = 0 then sorting based on column wise

array([[ 9,  1,  9,  2],
       [14,  1, 39, 26],
       [20,  8, 47, 31],
       [36, 35, 54, 38],
       [50, 72, 77, 43],
       [59, 81, 79, 68]])

In [12]:
np.sort(b,axis=1)
# to give axis =1 then sorting based on row wise

array([[14, 35, 38, 79],
       [ 1,  9, 26, 77],
       [ 2,  8, 50, 54],
       [ 1, 20, 47, 68],
       [39, 43, 59, 72],
       [ 9, 31, 36, 81]])

In [14]:
e=np.array([1,1,1,2,2,2,2,3,4,5,6,7,3])

np.unique(e)

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
a.shape

(15,)

In [17]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [21]:
b_expanded=np.expand_dims(b,axis=0).shape
print(b_expanded)

(1, 6, 4)


In [22]:
a

array([41, 84, 63, 91, 17, 93, 38, 34, 24, 30, 23, 50, 78, 33, 94])

In [26]:
np.where(a>50)

# np. where function return the indeses of the element witch satisfied the specific condition 

(array([ 1,  2,  3,  5, 12, 14]),)

In [28]:
np.where(a>50,0,a)

# replace all value is greater then 50 replce with 0

array([41,  0,  0,  0, 17,  0, 38, 34, 24, 30, 23, 50,  0, 33,  0])

In [30]:
np.where((a>50)&(a%2==0),0,a)

# multiple condition is also allowd when we are using the where

array([41,  0, 63, 91, 17, 93, 38, 34, 24, 30, 23, 50,  0, 33,  0])

In [35]:
print(a)
print(np.argmax(a))

# argmax return the maximum element index 

[41 84 63 91 17 93 38 34 24 30 23 50 78 33 94]
14


In [38]:
print(a)
print(np.argmin(a))

# argmin return the minimum element index

[41 84 63 91 17 93 38 34 24 30 23 50 78 33 94]
4


In [43]:
print(b)
print(np.argmin(b,axis=0))
print(np.argmin(b,axis=1))
# axis=0 will give me a every column minimum element index

[[14 35 79 38]
 [ 9  1 77 26]
 [50  8 54  2]
 [20  1 47 68]
 [59 72 39 43]
 [36 81  9 31]]
[1 1 5 2]
[0 1 3 1 2 2]


In [45]:
# cumsum()

print(a)
print(np.cumsum(a))

[41 84 63 91 17 93 38 34 24 30 23 50 78 33 94]
[ 41 125 188 279 296 389 427 461 485 515 538 588 666 699 793]


In [51]:
print(b)
print(np.cumsum(b))
# tihs will flat the array and convert it into 1D
print(np.cumsum(b,axis=0))
# this will calculate the cumsum column wise
print(np.cumsum(b,axis=1))
# this will calculate cumsum row wise

[[14 35 79 38]
 [ 9  1 77 26]
 [50  8 54  2]
 [20  1 47 68]
 [59 72 39 43]
 [36 81  9 31]]
[ 14  49 128 166 175 176 253 279 329 337 391 393 413 414 461 529 588 660
 699 742 778 859 868 899]
[[ 14  35  79  38]
 [ 23  36 156  64]
 [ 73  44 210  66]
 [ 93  45 257 134]
 [152 117 296 177]
 [188 198 305 208]]
[[ 14  49 128 166]
 [  9  10  87 113]
 [ 50  58 112 114]
 [ 20  21  68 136]
 [ 59 131 170 213]
 [ 36 117 126 157]]


In [55]:
print(a)
print(np.percentile(a,50))
print(np.percentile(a,5))
print(np.percentile(a,25))

[41 84 63 91 17 93 38 34 24 30 23 50 78 33 94]
41.0
21.2
31.5


In [57]:
print(a)
print(np.histogram(a,bins=[0,50,100]))

[41 84 63 91 17 93 38 34 24 30 23 50 78 33 94]
(array([8, 7]), array([  0,  50, 100]))


In [58]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])