Numpy array vs Python List

In [1]:
# speed test b/w numpy array and python list 


a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]

c=[]

import time

start=time.time()

for i in range(len(a)):
    c.append(a[i]+b[i])

print(time.time()-start)

1.5000815391540527


In [2]:
import numpy as np

a=np.arange(10000000)
b=np.arange(10000000,20000000)

start=time.time()
c=a+b
print(time.time()-start)

0.131669282913208


In [3]:
# Memory comparision b/w Numpy array and pyhon list

a=[i for i in range(100000000)]

import sys

sys.getsizeof(a)

835128600

In [4]:
a = np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)

10000112

Advanced Indexing

In [6]:
a=np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
print(a[1,2])
print(a[1:3,1:3])

6
[[ 5  6]
 [ 9 10]]


In [11]:
# Fancy Indexing
a

a[:,[0,3,1]]

array([[ 0,  3,  1],
       [ 4,  7,  5],
       [ 8, 11,  9],
       [12, 15, 13],
       [16, 19, 17],
       [20, 23, 21]])

In [14]:
a[[2,4,1],:]

array([[ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [ 4,  5,  6,  7]])

In [ ]:
# Boolean Indexing

a=np.random.randint(1,100,24).reshape(6,4)
a



array([[52, 45, 65, 41],
       [ 7, 52, 94, 55],
       [16, 19, 13, 30],
       [13, 39, 88, 65],
       [41, 72, 58, 81],
       [73, 19, 22, 43]])

In [19]:
a[a>50]

array([52, 65, 52, 94, 55, 88, 65, 72, 58, 81, 73])

In [20]:
a[a%2==0]

array([52, 52, 94, 16, 30, 88, 72, 58, 22])

In [21]:
a[(a>50)&(a%2==0)]

array([52, 52, 94, 88, 72, 58])

In [23]:
a[~(a%7==0)]

array([52, 45, 65, 41, 52, 94, 55, 16, 19, 13, 30, 13, 39, 88, 65, 41, 72,
       58, 81, 73, 19, 22, 43])

Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [29]:
a=np.arange(6).reshape(2,3)
b=np.arange(6,12).reshape(2,3)

print(a)
print(b)

print(a+b)
print(a*b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]
[[ 0  7 16]
 [27 40 55]]


In [30]:
# difference dimention

a=np.arange(6).reshape(2,3)
b=np.arange(3).reshape(1,3)

print(a)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


#### Broadcasting Rules

**1. Make the two arrays have the same number of dimensions.**<br>
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

**2. Make each dimension of the two arrays the same size.**<br>
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

In [32]:
# MORE EXAMPLE

a=np.arange(12).reshape(4,3)
b=np.arange(3)

print(a)
print(b)
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [35]:
a=np.arange(3).reshape(1,3)
b=np.arange(3).reshape(3,1)

print(a)
print(b)
print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [37]:
a=np.arange(3).reshape(1,3)
b=np.arange(4).reshape(4,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [40]:
a=np.array([1])
b=np.arange(4).reshape(2,2)
print(a)
print(b)
print(a+b)

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [44]:
a=np.arange(12).reshape(3,4)
b=np.arange(12).reshape(4,3)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

Working With mathematical Formula

In [47]:
a=np.arange(10)
a
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [48]:
actual= np.random.randint(1,50,25)
predicted=np.random.randint(1,50,25)



In [49]:
def mse(actual,predicted):
    return np.mean((actual-predicted)**2)

mse(actual,predicted)

np.float64(370.0)