In [ ]:
import numpy as np

a=np.array([1,2,3])
print(a)

print(type(a))

# array

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
np.array([[1,2,3],[4,5,6]])

# metrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.array([[[1,2,3],[4,5,6],[7,8,9]]])

# tensor 

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [10]:
np.arange(1,11,dtype=float)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
np.arange(1,11,dtype=float).reshape(5,2)

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [18]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.random.random((3,4))

array([[0.0965257 , 0.85225509, 0.25348136, 0.4404658 ],
       [0.68874935, 0.22510149, 0.84520275, 0.63189197],
       [0.07862795, 0.30794331, 0.9742018 , 0.89475486]])

In [23]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [24]:
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [25]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Array Atributes

In [33]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [ ]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

# ndim--> it will tell dimention of array

1
2
3


In [40]:
print(a1.shape)
print(a2.shape)
print(a3.shape)  

# (2,2,2)  -->first 2 tell how many 2-D array and next two 2 represent no of rows and columns

(10,)
(3, 4)
(2, 2, 2)


In [ ]:
print(a1.size)
print(a2.size)
print(a3.size)

# size -->represent multiplication of rows and columns. 

10
12
8


In [48]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)
# int32 --> 4 byte lay che
# ane int64 -->8 byte lay che


8
8
8


In [52]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [54]:
a3.dtype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Stacking

In [2]:
# Horizontal Stacking
import numpy as np
a4=np.arange(12).reshape(3,4)
print(a4)
a5=np.arange(12,24).reshape(3,4)
print(a5)
np.hstack((a4,a5))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [3]:
a4=np.arange(12).reshape(3,4)
print(a4)
a5=np.arange(12,24).reshape(3,4)
print(a5)
np.vstack((a4,a5))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
# flaten and revel

a=np.arange(12).reshape(3,4)
print(a)
b=a.flatten()
print(b)
b[0]=99
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[99  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
a=np.arange(12).reshape(3,4)
print(a)
b=a.ravel()
print(b)
b[0]=99
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[99  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
sales = np.array([
    [100, 120, 150],
    [200, 180, 220],
    [90, 110, 130]
])

print(sales.sum(axis=0))
# column wise sum karse
print(sales.sum(axis=1))
# row wise sum karse

[390 410 500]
[370 600 330]


In [18]:
a = np.array([[10, 20, 30]])

print(a.shape)

a.squeeze().shape

(1, 3)


(3,)

In [23]:
a=np.array([1,2,3])
b=a
print(id(a))
print(id(b))
print(a)
print(b)

b[0]=99
print(b)
print(a)

125930741244016
125930741244016
[1 2 3]
[1 2 3]
[99  2  3]
[99  2  3]


In [22]:
a=np.array([1,2,3])
b=a.view()
print(id(a))
print(id(b))
print(a)
print(b)

b[0]=99

print(a)
print(b)


125930741243056
125930741244304
[1 2 3]
[1 2 3]
[99  2  3]
[99  2  3]


In [26]:
a=np.array([1,2,3,4])
b=a.copy()
print(id(a))
print(id(b))
print(a)
print(b)

b[0]=99

print(a)
print(b)

125930741241904
125930741242480
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[99  2  3  4]
